server {
    listen 4001 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    error_page 497 =301 https://$host:$server_port$request_uri;
    client_max_body_size 2G;

    location ~* ^/static/(css|js|fonts|models)/ {
        root /var/www;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=2592000, immutable" always;
        access_log off;
    }

    location /static/ {
        root /var/www;
        try_files $uri =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
        access_log off;
    }

    location / {
        resolver 127.0.0.11 valid=10s ipv6=off;
        set $upstream https://census_counters_webservice_fr:4001;
        proxy_pass $upstream;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
